---
kind: pipeline
type: kubernetes
name: Image Unstable

platform:
    os: linux
    arch: arm

trigger:
  event:
  - push
  - tag

steps:
  - name: build
    image: docker-registry.pikube.dev:31443/drone-genuinetools-img:latest
    settings:
      repo: docker.io/cromrots/opa
      tags: unstable
      cache_from: docker.io/cromrots/opa:cache
      cache_to: docker.io/cromrots/opa:cache
      platform: linux/amd64,linux/arm64,linux/arm/v6,linux/arm/v7,linux/arm/v8
      password:
        from_secret: docker_pwd
      username:
        from_secret: docker_user
    resources:
      requests:
        cpu: 1500
        memory: 750MiB

  - name: test
    image: cromrots/opa:unstable
    pull: always

---
kind: pipeline
type: kubernetes
name: Image Production

platform:
    os: linux
    arch: arm

trigger:
  event:
  - tag

depends_on:
  - Image Unstable

steps:
  - name: build
    image: docker-registry.pikube.dev:31443/drone-genuinetools-img:latest
    settings:
      repo: docker.io/cromrots/opa
      auto_tag: true
      cache_from: docker.io/cromrots/opa:cache
      cache_to: docker.io/cromrots/opa:cache
      platform: linux/amd64,linux/arm64,linux/arm/v6,linux/arm/v7,linux/arm/v8
      password:
        from_secret: docker_pwd
      username:
        from_secret: docker_user
    resources:
      requests:
        cpu: 1500
        memory: 750MiB

---
kind: pipeline
type: kubernetes
name: Notify Status

clone:
  disable: true

trigger:
  status:
  - success
  - failure

depends_on:
- Image Unstable
- Image Production

platform:
  os: linux
  arch: arm

steps:
  - name: discord notification
    image: appleboy/drone-discord
    settings:
      webhook_id:
        from_secret: discord_id
      webhook_token:
        from_secret: discord_token
      username: drone.io
      color: auto
      message: >
        <:openpolicyagent:950119352181600286> **{{repo.name}}**

        {{#success build.status}}
        :white_check_mark: {{build.event}} build {{build.number}} succeeded. Good job.
        {{else}}
        :warning: {{build.event}} build {{build.number}} failed. Fix me please.
        {{/success}}

        {{build.link}}

        **Branch:** {{commit.branch}} {{commit.tag}}

        **Message:** {{commit.message}}

---
kind: signature
hmac: 28cacd675a140321e7ce0fb84fa0411028033625739c95ebaa08d347f8142f85

...
